### ISSUE TITLE
question on keras used in different files

### ISSUE THREAD

**Issue by AgentDS** [wyjeong/FedMatch#3]
Hi, really appreciate your work. But I am confused that why you used `tf.keras` in some files while `tf.python.keras` in others? I am not familiar with tensorflow, could you please explain this?

**Comment by wyjeong** [comment]
Hi There,

Thank you for your interest.  The file which imports `tf.python.keras` is based on the official `tensorflow` source codes for Dense and Conv layers (I just adopted the code as mentioned in the comment). Except for the case, `tf.keras` modules are used by default. Please let me know anything else you want to clarify :) Thanks!

**Comment by AgentDS** [comment]
got it! thx!
